### ISSUE TITLE
秒退

### ISSUE THREAD

**Issue by lefttt** [lkjie/paper-translate#3]
复制网页中pdf的文字时，老版本只是给出错误但不秒退，新版本秒退，然后查看错误为：

'gbk' codec can't encode character '\u2212' in position 148: illegal multibyte sequence

**Comment by lefttt** [comment]
写论文神器，我离不开你啊，求大佬帮忙

**Comment by lkjie** [comment]
可能是存储文件无法保存utf8字符导致的，请更新脚本，删除目录下的sourceList.json和translated.json，然后重试

**Comment by LiuJMzzZ** [comment]
复制某些文本秒退后，命令行里的错误代码
'paperTran'
Traceback (most recent call last):
  File "paperTran.py", line 202, in restoreTimeOut
    self.form.restore()
  File "paperTran.py", line 169, in restore
    json.dump(self.sourceList, open(self.RES_PATH, 'w'), ensure_ascii=False, indent=4)
  File "C:\Users\dm\Anaconda3\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
UnicodeEncodeError: 'gbk' codec can't encode character '\xb5' in position 201: illegal multibyte sequence
请按任意键继续. . .

**Comment by lkjie** [comment]
> 复制某些文本秒退后，命令行里的错误代码
> 'paperTran'
> Traceback (most recent call last):
> File "paperTran.py", line 202, in restoreTimeOut
> self.form.restore()
> File "paperTran.py", line 169, in restore
> json.dump(self.sourceList, open(self.RES_PATH, 'w'), ensure_ascii=False, indent=4)
> File "C:\Users\dm\Anaconda3\lib\json__init__.py", line 180, in dump
> fp.write(chunk)
> UnicodeEncodeError: 'gbk' codec can't encode character '\xb5' in position 201: illegal multibyte sequence
> 请按任意键继续. . .

由于windows和*nix系统的编码问题，导致此问题。已经统一了各平台的编码格式为utf8，请更新代码，删除sourceList.json和translated.json文件，重新使用即可。
